name: osx-arm64 AOT Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.100-preview.3.21202.5
    - name: Restore dependencies
      run: dotnet restore
    - name: AOT build
      run: dotnet publish -r osx-arm64 -c Release
      working-directory: ./backend/wave.backend.ishtar.light
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2.2.3
      with:
        name: osx-aot-build
        path: ./backend/wave.backend.ishtar.light/bin/Release/net6.0/osx-arm64/native
        if-no-files-found: error
